id: I64FF33BC
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T16:11:11.326986'
last_modified: '2022-05-27T16:11:11.326999'
parser: null
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: en
  base:
    f5C49:
      title: Complete text
      base_file: f5C49.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
